// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SaLes__APIs.Entity;

public partial class Customer
{
    public Customer()
    {
        CustomId = Guid.NewGuid();
    }
    public Guid CustomId { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }
     
    public int? CountryCode { get; set; }
    [JsonIgnore]
    public int? OptimisticLockField { get; set; }
    [JsonIgnore]
    public int? GCRecord { get; set; }
    [JsonIgnore]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}