// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaLes__APIs.Entity;

public partial class PermissionPolicyUserUsers_PermissionPolicyRoleRole
{
    [Key]
    public Guid? Roles { get; set; }

    public Guid? Users { get; set; }

    public Guid OID { get; set; }

    public int? OptimisticLockField { get; set; }

    public virtual PermissionPolicyRole RolesNavigation { get; set; }

    public virtual PermissionPolicyUser UsersNavigation { get; set; }
}