// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaLes__APIs.Entity;

public partial class PermissionPolicyTypePermissionsObject
{
    [Key]
    public Guid Oid { get; set; }

    public Guid? Role { get; set; }

    public string TargetType { get; set; }

    public int? ReadState { get; set; }

    public int? WriteState { get; set; }

    public int? CreateState { get; set; }

    public int? DeleteState { get; set; }

    public int? NavigateState { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? GCRecord { get; set; }

    public virtual ICollection<PermissionPolicyMemberPermissionsObject> PermissionPolicyMemberPermissionsObjects { get; set; } = new List<PermissionPolicyMemberPermissionsObject>();

    public virtual ICollection<PermissionPolicyObjectPermissionsObject> PermissionPolicyObjectPermissionsObjects { get; set; } = new List<PermissionPolicyObjectPermissionsObject>();

    public virtual PermissionPolicyRole RoleNavigation { get; set; }
}