// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaLes__APIs.Entity;

public partial class PermissionPolicyNavigationPermissionsObject
{
    [Key]
    public Guid Oid { get; set; }

    public string ItemPath { get; set; }

    public int? NavigateState { get; set; }

    public Guid? Role { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? GCRecord { get; set; }

    public virtual PermissionPolicyRole RoleNavigation { get; set; }
}