// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaLes__APIs.Entity;

public partial class PermissionPolicyUserLoginInfo
{
    [Key]
    public Guid Oid { get; set; }

    public string LoginProviderName { get; set; }

    public string ProviderUserKey { get; set; }

    public Guid? User { get; set; }

    public int? OptimisticLockField { get; set; }

    public virtual PermissionPolicyUser UserNavigation { get; set; }
}