// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SaLes__APIs.Entity;

public partial class Product
{
    public Product()
    {
        Oid = Guid.NewGuid();
    }
    public Guid Oid { get; set; }

    public string Name { get; set; }

    public int? Quantity { get; set; }

    public double? CostPrice { get; set; }

    public double? SelaPrice { get; set; }

    public Guid? Image { get; set; }

    public Guid? RowInvoice { get; set; }
    [JsonIgnore]
    public int? OptimisticLockField { get; set; }
    [JsonIgnore]
    public int? GCRecord { get; set; }
    [JsonIgnore]
    public virtual MediaDataObject ImageNavigation { get; set; }
    [JsonIgnore]
    public virtual RowInvoice RowInvoiceNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<RowInvoice> RowInvoices { get; set; } = new List<RowInvoice>();
}