// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaLes__APIs.Entity;

public partial class Supplier
{
    [Key]
    public Guid Oid { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public int? OptimisticLockField { get; set; }

    public int? GCRecord { get; set; }
}