// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaLes__APIs.Entity;

public partial class XPObjectType
{
    [Key]
    public int OID { get; set; }

    public string TypeName { get; set; }

    public string AssemblyName { get; set; }

    public virtual ICollection<PermissionPolicyRole> PermissionPolicyRoles { get; set; } = new List<PermissionPolicyRole>();

    public virtual ICollection<PermissionPolicyUser> PermissionPolicyUsers { get; set; } = new List<PermissionPolicyUser>();
}